name: sorted_collection
description: An implementation of a sorted list for Dart.
version: 1.0.0
repository: https://github.com/tomasweigenast/dart-sorted-list

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
# dependencies: 
#   collection: ^1.15.0
