name: dart_sorted_list
description: An implementation of the C# SortedList for Dart
version: 1.0.0

environment:
  sdk: '>=2.16.0-80.1.beta <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
# dependencies: 
#   collection: ^1.15.0
